### PR TITLE
Fix CLI example

### PR DESCRIPTION
**Pull request by Dosenpfand**
To make the CLI example buildable i had to perform the included changes. Otherwise, i would get the following error when trying to build with Rust 1.57.0:
```
cargo run --example cli
   Compiling odoh-rs v1.0.0-alpha.1 (odoh-rs)
  --> examples\cli.rs:10:17
   |
10 | use rand::{Rng, SeedableRng};
   |                 ^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

error[E0599]: no function or associated item named `from_entropy` found for struct `StdRng` in the current scope
  --> examples\cli.rs:69:27
   |
69 |     let mut rng = StdRng::from_entropy();
   |                           ^^^^^^^^^^^^ function or associated item not found in `StdRng`

warning: unused import: `Rng`
  --> examples\cli.rs:10:12
   |
10 | use rand::{Rng, SeedableRng};
   |            ^^^

For more information about this error, try `rustc --explain E0599`.
warning: `odoh-rs` (example "cli") generated 2 warnings
error: could not compile `odoh-rs` due to previous error; 2 warnings emitted
'''

### CODE REVIEW

File: Cargo.toml [hunk 1]
```diff
@@ -29,6 +29,7 @@ reqwest = "0.11"
 serde = { version = "1.0", features = ["derive"] }
 serde_json = "1.0"
 tokio = { version = "1", features = [ "full" ] }
+rand = { version = "0.8", features = [ "std_rng", "getrandom" ], default-features = false }
```
Comment (xofyarg) [inline Cargo.toml]: `getrandom` is included in the default feature set, so you can just have `rand = "0.8"`, and have the deps sorted(`cargo add -s` will do :)

File: examples/cli.rs [hunk 2]
```diff
@@ -6,8 +6,8 @@ use domain::base::{Dname as DnameO, Message, MessageBuilder, ParsedDname, Rtype}
 use domain::rdata::AllRecordData;
 use log::{info, trace};
 use odoh_rs::*;
+use rand::prelude::*;
 use rand::rngs::StdRng;
-use rand::{Rng, SeedableRng};
```
Comment (xofyarg) [inline examples/cli.rs]: This change is not really needed as long  as the feature been updated above.

File: Cargo.toml (hunk 1 above)
Comment (Dosenpfand) [reply Cargo.toml]: Thanks for the hint, I adapted it accordingly.

File: examples/cli.rs (hunk 2 above)
Comment (Dosenpfand) [reply examples/cli.rs]: Reverted.

**Comment by xofyarg** [comment]
Merged, thanks for the fix.
